-- Used postgres --
-- Table: users --

create table users (
    id bigint not null generated by default as identity primary key,
    username varchar(255) not null,
    email varchar(255) not null,
    password varchar(255) not null
);

-- Table: roles --

create table roles (
    id bigint not null generated by default as identity primary key,
    name varchar(255)
);

-- Table for mapping: user_roles --

create table user_roles(
    user_id bigint not null,
    role_id bigint not null,

    foreign key (user_id) references users(id),
    foreign key (role_id) references roles(id),

    unique (user_id, role_id)
);


-- Insert data --

insert into users values (1, 'admin', 'admin@admin.ru', 'admin');
insert into roles values (1, 'ROLE_ADMIN');
insert into roles values (2, 'ROLE_USER');
insert into user_roles values (1, 1);